#!/usr/bin/env python3
"""Canonical prose store for TGI post copy.

Why this exists: card copy used to live inside ~25 separate build-*.py scripts,
and 11 of the 23 recent posts no longer have a working builder at all. That made
a site-wide voice rewrite impossible to do once and keep. The deck is now the
single source of truth for product-card descriptions and section kickers.

    python3 copy-deck.py extract      # scaffold/refresh the deck from live HTML
    python3 copy-deck.py apply        # write deck prose into drops/*.html
    python3 copy-deck.py apply --dry  # show what would change
    python3 copy-deck.py status       # how much of the deck has been rewritten

Deck shape — data/copy-deck.json:

    { "<post-slug>": {
        "cards":   { "<card-id>": { "name": "...", "meta": "...",
                                    "desc": "<live/new copy>",
                                    "old":  "<pre-rewrite copy, kept for diffing>",
                                    "done": true } },
        "kickers": { "<n>": { "label": "...", "text": "...",
                              "old": "...", "done": true } } } }

`extract` never overwrites an entry marked "done": true, so it is safe to re-run
after a rebuild. `apply` is idempotent and only touches the two prose slots.
"""
import re, os, sys, json, html

ROOT = os.path.dirname(os.path.abspath(__file__))
DECK = os.path.join(ROOT, "data", "copy-deck.json")
SINCE = "2026-08-14"

# Cards are keyed by their id= when they have one and by ordinal position when
# they don't — 11 of the 23 posts were generated by scripts that never emitted ids.
CARD_RE = re.compile(
    r'<div class="product-card"([^>]*)>.*?'
    r'<div class="product-name">(.*?)</div>.*?'
    r'<div class="product-desc">(.*?)</div>', re.S)
WRAP_RE = re.compile(r'(<div class="writeup-body"[^>]*>)(.*?)(</div>)', re.S)
PARA_RE = re.compile(r'<p[^>]*>.*?</p>', re.S)
KICK_RE = re.compile(r'(<p class="cat-kicker">)(?:(<strong>.*?</strong>))?(.*?)(</p>)', re.S)


def card_key(attrs, ordinal):
    m = re.search(r'id="([^"]+)"', attrs)
    return m.group(1) if m else f"#{ordinal}"


def recent_posts():
    out = []
    for f in sorted(os.listdir(os.path.join(ROOT, "drops"))):
        if not f.endswith(".html"):
            continue
        p = os.path.join(ROOT, "drops", f)
        h = open(p, encoding="utf-8").read()
        m = re.search(r'datePublished"\s*:\s*"([\d-]+)', h)
        if m and m.group(1) >= SINCE:
            out.append((f[:-5], p))
    return out


def load():
    if os.path.exists(DECK):
        return json.load(open(DECK, encoding="utf-8"))
    return {}


def save(d):
    os.makedirs(os.path.dirname(DECK), exist_ok=True)
    json.dump(d, open(DECK, "w", encoding="utf-8"), indent=1, ensure_ascii=False)


def extract():
    deck = load()
    added = kept = 0
    for slug, path in recent_posts():
        h = open(path, encoding="utf-8").read()
        post = deck.setdefault(slug, {"cards": {}, "kickers": {}, "writeup": {}})
        post.setdefault("writeup", {})
        wm = WRAP_RE.search(h)
        if wm:
            for i, para in enumerate(PARA_RE.findall(wm.group(2))):
                k = str(i + 1)
                e = post["writeup"].get(k)
                if e and e.get("done"):
                    kept += 1
                    continue
                post["writeup"][k] = {"html": para, "old": para, "done": False}
                added += 1
        for i, (attrs, name, desc) in enumerate(CARD_RE.findall(h)):
            cid = card_key(attrs, i + 1)
            e = post["cards"].get(cid)
            if e and e.get("done"):
                kept += 1
                continue
            post["cards"][cid] = {
                "name": re.sub(r"<[^>]+>", "", name).strip(),
                "desc": desc.strip(), "old": desc.strip(), "done": False}
            added += 1
        for i, (_, label, text, _) in enumerate(KICK_RE.findall(h)):
            k = str(i + 1)
            e = post["kickers"].get(k)
            if e and e.get("done"):
                kept += 1
                continue
            post["kickers"][k] = {
                "label": (label or "").strip(),
                "text": text.strip(), "old": text.strip(), "done": False}
            added += 1
    save(deck)
    print(f"deck: {len(deck)} posts | {added} slot(s) scaffolded | {kept} rewritten slot(s) preserved")


def apply(dry=False):
    deck = load()
    total = 0
    for slug, path in recent_posts():
        post = deck.get(slug)
        if not post:
            continue
        h = open(path, encoding="utf-8").read()
        orig = h
        n = 0

        cidx = [0]

        def sub_card(m):
            nonlocal n
            cidx[0] += 1
            desc = m.group(3)
            e = post.get("cards", {}).get(card_key(m.group(1), cidx[0]))
            if not e or not e.get("done") or e["desc"].strip() == desc.strip():
                return m.group(0)
            n += 1
            return m.group(0)[:m.start(3) - m.start(0)] + e["desc"] + m.group(0)[m.end(3) - m.start(0):]

        h = CARD_RE.sub(sub_card, h)

        idx = [0]

        def sub_kick(m):
            idx[0] += 1
            e = post.get("kickers", {}).get(str(idx[0]))
            if not e or not e.get("done") or e["text"].strip() == m.group(3).strip():
                return m.group(0)
            nonlocal n
            n += 1
            return m.group(1) + (e.get("label") or m.group(2) or "") + e["text"] + m.group(4)

        h = KICK_RE.sub(sub_kick, h)

        def sub_wrap(m):
            nonlocal n
            paras = PARA_RE.findall(m.group(2))
            wd = post.get("writeup", {})
            if not any(wd.get(str(i + 1), {}).get("done") for i in range(len(paras))):
                return m.group(0)
            out, body = [], m.group(2)
            for i, para in enumerate(paras):
                e = wd.get(str(i + 1))
                out.append(e["html"] if (e and e.get("done")) else para)
            for i, para in enumerate(paras):
                if out[i] != para:
                    body = body.replace(para, out[i], 1); n += 1
            return m.group(1) + body + m.group(3)

        h = WRAP_RE.sub(sub_wrap, h)

        if h != orig:
            total += n
            if dry:
                print(f"  would update {slug}: {n} slot(s)")
            else:
                open(path, "w", encoding="utf-8").write(h)
                print(f"  updated {slug}: {n} slot(s)")
    print(f"{'would write' if dry else 'wrote'} {total} prose slot(s)")


def status():
    deck = load()
    tc = td = kc = kd = 0
    rows = []
    for slug, post in sorted(deck.items()):
        c = post.get("cards", {}); k = post.get("kickers", {}); w = post.get("writeup", {})
        cd = sum(1 for v in c.values() if v.get("done"))
        kd_ = sum(1 for v in k.values() if v.get("done"))
        wd_ = sum(1 for v in w.values() if v.get("done"))
        tc += len(c); td += cd; kc += len(k) + len(w); kd += kd_ + wd_
        rows.append((slug, cd, len(c), kd_, len(k)))
    w = max((len(r[0]) for r in rows), default=10)
    for slug, cd, ct, k1, kt in rows:
        bar = "DONE" if cd == ct and k1 == kt else f"{cd}/{ct} cards, {k1}/{kt} kickers"
        print(f"  {slug:<{w}}  {bar}")
    print(f"\n{td}/{tc} cards rewritten | {kd}/{kc} kickers rewritten")


if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "status"
    if cmd == "extract": extract()
    elif cmd == "apply": apply("--dry" in sys.argv)
    else: status()
