#!/usr/bin/env python3
"""wire-vuori.py — wire the Vuori Brand to Know. 21 September 2026.

Six jobs:
  1. homepage card, 5 slides, in the TOP slot of the feed
  2. window._slideTexts registry (ONE underscore — see below)
  3. data/brands.json — REPOINT the existing Vuori row at the new post
  4. scan-new-brand-mentions domain map + the /brands rebuild chain
  5. sitemap lastmod
  6. search index

WHY THIS SCRIPT RUNS THE /brands CHAIN ITSELF.

On the Late Nine wire, this script's predecessor wrote the brands.json row,
guarded that the row existed, reported success — and Late Nine never appeared
on /brands. data/brands.json is not the brand index; it is the *input* to it.
The page is generated by build-brands.py and then rebuilt into the approved
design by build-brand-index.py, and neither had been run. The guard verified
the artifact this script produced instead of the artifact the reader opens,
which is the same mistake as verifying image FILES and not the render.

So the chain runs here, in order, and the guard reads brands/index.html.

VUORI IS ALREADY IN THE INDEX, POINTING AT THE WRONG PAGE.
Unlike Late Nine, Vuori has been in brands.json since 4 September, with its
url set to /drops/10-technical-fabric-tops-for-summer — a roundup it appears
in, not a page about it. This repoints the row and refreshes its line, tags
and lead image. It does NOT add a second row; a duplicate slug is guarded.

NO HTML ENTITIES IN brands.json. The Late Nine row was written with
"Maxim Lundh&rsquo;s" and rendered as literal "&rsquo;" on the index card —
it was the only one of 137 rows using entities. Real unicode only, guarded.
"""
import json
import pathlib
import re
import subprocess
import sys
from datetime import date

ROOT = pathlib.Path(__file__).resolve().parent
INDEX = ROOT / "index.html"
BRANDS = ROOT / "data/brands.json"
MENTIONS_SCRIPT = ROOT / "scan-new-brand-mentions.py"
SITEMAP = ROOT / "sitemap.xml"

SLUG = "brand-to-know-vuori"
KEY = "vuori"
MARK = "<!-- BRAND TO KNOW — VUORI -->"
ANCHOR = "<!--TGI-SC-HOME-->"
TITLE = "Brand to Know &mdash; Vuori"
TODAY = date.today().isoformat()

# The five Lenny approved off the 18-grid: 1, 3, 17, 11, 8.
SLIDES = [
    ("aim-trouser", "https://vuoriclothing.com/products/aim-trouser-athletic-slim-fit-30-khaki-linen-texture",
     "The magnetic pocket", "Aim Trouser Athletic Slim Fit &middot; $98"),
    ("strato-tech-polo", "https://vuoriclothing.com/products/strato-tech-polo-navy-heather",
     "Cheapest way in", "Strato Tech Polo &middot; $68"),
    ("meta-trouser", "https://vuoriclothing.com/products/vuori-meta-trouser-classic-fit-30-french-roast",
     "In both collections at once", "Vuori Meta&trade; Trouser Classic Fit &middot; $138"),
    ("kore-short", "https://vuoriclothing.com/products/kore-unlined-short-black",
     "The piece that built the company", "Kore Short Unlined 7&Prime; &middot; $68"),
    ("terrain-jacket", "https://vuoriclothing.com/products/terrain-jacket-black",
     "Named in the May launch", "Terrain Jacket &middot; $138"),
]

SLIDE_TEXTS = [
    "Athletic-slim, lightweight technical fabric, and a back pocket that shuts "
    "with a magnet instead of a button. The most golf-specific thing Vuori makes, "
    "and it landed with the May collection. $98.",
    "Flagged a best seller in four separate colourways and the cheapest entry to "
    "the golf line. Heathered, soft-collared, no logo doing any work. $68.",
    "This trouser sits in the golf collection and the general pants collection at "
    "the same time, same name, same price. The whole argument in one garment. $138.",
    "The piece that built the company, back when it was selling into yoga studios "
    "and barely moving. Runs 5, 7 and 9in, lined or unlined. $68.",
    "The outerwear piece of the golf range. Plain black shell, zip front, nothing "
    "on it. $138.",
]

CARD_TEXT = ("Athletic-slim, lightweight technical fabric, and a back pocket that "
             "shuts with a magnet instead of a button. The most golf-specific thing "
             "Vuori makes, and it landed with the May collection. $98.")

# The repointed index row. Real unicode, no HTML entities — see the docstring.
BRAND_ROW = {
    "slug": "vuori",
    "name": "Vuori",
    "loc": "Carlsbad, California",
    "regions": ["usa"],
    "cats": ["apparel", "accessories"],
    "line": "Joe Kudla's Encinitas-born activewear label, now in golf behind Tom "
            "Holland — and still best at the off-course half of the wardrobe.",
    "url": f"/drops/{SLUG}",
    "tags": ["post-round-friendly"],
    "attrs": [],
    "added": "2026-09-04",
    "img": "/images/vuori/strato-tech-polo.jpg",
}


def card_html():
    slides = "\n".join(
        f'          <div class="gear-slide">\n'
        f'            <a href="{href}" target="_blank" rel="noopener">\n'
        f'              <img src="/images/vuori/{slug}.jpg" alt="Vuori {re.sub(r"&[a-zA-Z]+;", "", name)}" loading="lazy" />\n'
        f'              <div class="gear-slide-info"><div class="gear-slide-brand">{kick}</div>'
        f'<div class="gear-slide-name">{name}</div></div>\n'
        f'            </a>\n'
        f'          </div>'
        for slug, href, kick, name in SLIDES)
    return f'''{MARK}
  <div class="card" data-type="drop">
    <div class="card-media" style="position:relative;">
      <span class="card-tag grass">[Drops &amp; Brands]</span>
      <div class="gear-carousel" data-carousel="{KEY}">
        <div class="gear-carousel-track">
{slides}
        </div>
        <button class="gear-arrow prev" onclick="gearSlide(this, -1)">&#8249;</button>
        <button class="gear-arrow next" onclick="gearSlide(this, 1)">&#8250;</button>
      </div>
    </div>
    <div class="card-body">
      <div class="card-title"><a href="/drops/{SLUG}" style="color:inherit;text-decoration:none;border-bottom:none;">{TITLE}</a></div>
      <div class="card-text" data-slidetext="{KEY}">{CARD_TEXT}</div>
      <div class="gear-dots" data-dots="{KEY}"></div>
      <div class="gear-counter" data-counter="{KEY}">1 / {len(SLIDES)}</div>
      <a href="/drops/{SLUG}" class="card-link">Read the profile &#8599;</a>
    </div>
  </div>
'''


def card_bounds(h):
    """(start, end) of an existing Vuori card, or (-1, -1). Finds by MARK first,
    then by a link to our slug — a marker-only lookup can only find cards this
    script wrote, which is how a duplicate gets created."""
    i = h.find(MARK)
    if i < 0:
        hit = h.find(f"/drops/{SLUG}")
        if hit < 0:
            return -1, -1
        i = h.rfind('<div class="card"', 0, hit)
        if i < 0:
            sys.exit("! found a link to the post but no card around it")
    j = min((x for x in (h.find('class="card-link"', i),
                         h.find('class="card-readmore"', i)) if x > 0), default=-1)
    if j < 0:
        sys.exit("! card found but no card-link/card-readmore to bound it")
    j = h.find("</div>", h.find("</a>", j))
    j = h.find("</div>", j + 6) + 6
    k = h.rfind("\n", 0, i) + 1
    if h[k:i].strip() == "":
        i = k
    while j < len(h) and h[j] == "\n":
        j += 1
    return i, j


def wire_index(h):
    """Cut-then-paste into the TOP slot. A move that leaves the original behind
    is the duplicate-card bug in a new costume; the card count is guarded."""
    if ANCHOR not in h:
        sys.exit("! feed anchor not found")
    new = card_html().strip()
    notes = []
    i, j = card_bounds(h)
    if i >= 0:
        old = h[i:j]
        if old.count('<div class="card"') != 1:
            sys.exit("! card bounds wrong — slice holds more than one card")
        was_top = h[:i].rstrip().endswith(ANCHOR)
        notes.append("card already current" if old.strip() == new else "card REPLACED")
        notes.append("card already in top slot" if was_top else "card MOVED to top slot")
        h = h[:i] + h[j:]
    else:
        notes.append("card inserted in top slot")
    return h.replace(ANCHOR, ANCHOR + "\n  " + new + "\n", 1), notes


def wire_slidetexts(h):
    """The CENTRAL registry — window._slideTexts, ONE underscore. Inline
    __slideTexts blocks exist on this page and the slider never reads them."""
    lines = ",\n".join('      "' + t.replace('"', '\\"') + '"' for t in SLIDE_TEXTS)
    block = f'"{KEY}": [\n{lines}\n    ],'
    anchor = "window._slideTexts = {"
    if anchor not in h:
        sys.exit("! window._slideTexts registry not found")
    existing = re.search(rf'"{KEY}": \[.*?\n    \],', h, re.S)
    if existing:
        if existing.group(0) == block:
            return h, ["slideTexts already current"]
        return h[:existing.start()] + block + h[existing.end():], ["slideTexts REPLACED"]
    return h.replace(anchor, anchor + "\n    " + block, 1), ["slideTexts added"]


def wire_brands(rows):
    hits = [r for r in rows if r["slug"] == "vuori"]
    if len(hits) > 1:
        sys.exit(f"! {len(hits)} vuori rows already in brands.json")
    if hits:
        if hits[0] == BRAND_ROW:
            return rows, ["brands.json row already current"]
        old_url = hits[0].get("url", "")
        rows[rows.index(hits[0])] = dict(BRAND_ROW)
        return rows, [f"brands.json REPOINTED ({old_url} -> {BRAND_ROW['url']})"]
    rows.append(dict(BRAND_ROW))
    rows.sort(key=lambda r: r["name"].lower())
    return rows, ["brands.json row added"]


def wire_sitemap(x):
    if f"/drops/{SLUG}" in x:
        x2 = re.sub(rf"(<loc>https://thegrassyissue\.com/drops/{re.escape(SLUG)}</loc>\s*"
                    rf"<lastmod>)[^<]*(</lastmod>)",
                    lambda m: m.group(1) + TODAY + m.group(2), x)
        return x2, ["sitemap lastmod refreshed" if x2 != x else "sitemap already current"]
    entry = (f"  <url>\n    <loc>https://thegrassyissue.com/drops/{SLUG}</loc>\n"
             f"    <lastmod>{TODAY}</lastmod>\n  </url>\n")
    return x.replace("</urlset>", entry + "</urlset>"), ["sitemap entry added"]


# THE SEARCH INDEX IS GENERATED, NOT EDITED.
#
# The first draft of this script hand-wrote a row into data/search-index.json.
# Two things were wrong with that. The file is not there — it is /search-index
# .json at the site root — and, more to the point, it is built from every page
# on the site by generate-search-index.py. Hand-writing a row into a derived
# artifact is the same error as writing data/brands.json and expecting /brands
# to change: it puts a value in the output and leaves the generator's own view
# of the world untouched, so the next regeneration silently drops it.
#
# So there is no wire_search(). generate-search-index.py runs in the chain in
# main(), and the guard reads the file it produced.
SEARCH = ROOT / "search-index.json"


def run(cmd, label):
    r = subprocess.run([sys.executable, str(ROOT / cmd[0])] + cmd[1:],
                       cwd=ROOT, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit(f"! {label} failed:\n{r.stdout[-1500:]}{r.stderr[-1500:]}")
    return r.stdout


def main(apply_):
    h = INDEX.read_text(encoding="utf-8")
    rows = json.loads(BRANDS.read_text(encoding="utf-8"))
    x = SITEMAP.read_text(encoding="utf-8")
    cards_before = h.count('<div class="card"')

    # A MOVE keeps the card count; an INSERT adds one. Late Nine was a move and
    # this guard was written for that case, so on Vuori — which had no card at
    # all — it failed a correct page. Expected count comes from what was found,
    # not from an assumption about which of the two this run is.
    had_card = card_bounds(h)[0] >= 0

    h2, c1 = wire_index(h)
    h2, c2 = wire_slidetexts(h2)
    rows2, c3 = wire_brands(rows)
    x2, c4 = wire_sitemap(x)
    for c in c1 + c2 + c3 + c4:
        print("  " + c)
    if not apply_:
        print("\n  dry run — pass --apply")
        return

    INDEX.write_text(h2, encoding="utf-8")
    BRANDS.write_text(json.dumps(rows2, indent=2, ensure_ascii=False) + "\n",
                      encoding="utf-8")
    SITEMAP.write_text(x2, encoding="utf-8")

    # ---- THE /brands CHAIN. Not optional, and order matters: build-brands.py
    # is an intermediate step that reverts /brands to the old design on its
    # own, and build-brand-index.py is what produces the page that ships.
    print("\n  rebuilding the brand index:")
    run(["scan-new-brand-mentions.py", "--apply"], "scan-new-brand-mentions")
    print("    · mentions map refreshed")
    run(["build-brands.py"], "build-brands")
    print("    · brands/ regenerated")
    run(["build-brand-index.py", "--apply"], "build-brand-index")
    print("    · approved /brands design rebuilt")
    run(["generate-search-index.py"], "generate-search-index")
    print("    · search index regenerated")

    # ---- VERIFY THE FINISHED FILES, AND THE BRAND INDEX PAGE ITSELF ----
    hh = INDEX.read_text(encoding="utf-8")
    rr = json.loads(BRANDS.read_text(encoding="utf-8"))
    bi = (ROOT / "brands/index.html").read_text(encoding="utf-8")
    bad = []

    if hh.count(MARK) != 1: bad.append(f"{hh.count(MARK)} cards, expected 1")
    i = hh.find(MARK)
    gap = hh[hh.find(ANCHOR) + len(ANCHOR):i]
    if gap.strip():
        bad.append(f"card is not first in the feed — {gap.strip()[:50]!r} sits above it")
    want_cards = cards_before if had_card else cards_before + 1
    got_cards = hh.count('<div class="card"')
    if got_cards != want_cards:
        bad.append(f"feed has {got_cards} cards, expected {want_cards}")
    seg = hh[i:hh.find("</div>\n", hh.find('class="card-link"', i))]
    if seg.count('<div class="gear-slide">') != len(SLIDES):
        bad.append("slide count wrong")
    if hh.count(f'data-carousel="{KEY}"') != 1:
        bad.append(f"carousel key {KEY!r} is not unique")
    for m in re.finditer(r'<img src="([^"]+)"', seg):
        s = m.group(1)
        if s.startswith("http"): bad.append(f"hot-linked slide image: {s[:50]}")
        elif not (ROOT / s.lstrip("/")).is_file(): bad.append(f"missing image {s}")
    for pat in (r"\bSEK\b", r"\bkr\b"):
        if re.search(pat, seg): bad.append(f"non-USD currency in the card: {pat}")

    si = json.loads(SEARCH.read_text(encoding="utf-8"))
    if not any(r.get("u") == f"/drops/{SLUG}" for r in si):
        bad.append("the post is not in the generated search index")

    reg = re.search(r"window\._slideTexts = \{(.*?)\n  \};", hh, re.S)
    if not reg or f'"{KEY}"' not in reg.group(1):
        bad.append(f"{KEY!r} is not in the _slideTexts registry")

    ent = [r for r in rr if r.get("slug") == "vuori"]
    if len(ent) != 1:
        bad.append(f"{len(ent)} brands.json rows for vuori, expected 1")
    elif ent[0]["url"] != f"/drops/{SLUG}":
        bad.append(f"brands.json still points at {ent[0]['url']}")
    for r in rr:
        for f in ("line", "name", "loc"):
            if isinstance(r.get(f), str) and re.search(r"&[a-z]+;", r[f]):
                bad.append(f"HTML entity in brands.json {r['slug']}.{f}")

    # THE PAGE, NOT THE DATA — the check that was missing on the Late Nine wire
    if "Vuori" not in bi:
        bad.append("Vuori is not on the rendered /brands index")
    if f"/brands/vuori" not in bi:
        bad.append("no /brands/vuori link on the index")
    if not (ROOT / "brands/vuori.html").is_file():
        bad.append("brands/vuori.html was not generated")
    if 'id="bx"' not in bi:
        bad.append("/brands lost the approved design — build-brand-index.py did not run")
    n_links = len(set(re.findall(r'/brands/([a-z0-9-]+)"', bi)))
    if n_links != len(rr):
        bad.append(f"{n_links} brand links on /brands for {len(rr)} brands in the data")

    if bad:
        sys.exit("! " + "; ".join(bad))
    print(f"\n  verified: card in top slot ({len(SLIDES)} slides), slideTexts, "
          f"brands.json repointed, /brands rebuilt with {len(rr)} brands")


if __name__ == "__main__":
    main("--apply" in sys.argv)
