import html,json
# (id, name, cuisine, where, hours, order, why, status, flag, rec, url)
O=[
("F01","Gimme Burger","Smash burgers","Butler Pitch & Putt, 201 Lee Barton Dr · Zilker","Daily 12–8; breakfast sandwiches Fri–Sun 8–11","Double smash with American cheese; fried okra","The only truck actually parked on an Austin muni. Michael Fojtasek (Olamaie) runs the food.","Open","",1,"https://butlerpitchandputt.com/eat-drink"),
("F02","Two Goose Market & Barbecue","Breakfast + BBQ","706 N Lamar · Clarksville","Wed–Sat 7–2, Sun 10–2","Big Honkin' breakfast burrito $16; Tallest Man $12","Opened Dec 2025; Texas Monthly review Feb 2026; #2 on Southern Living's best new BBQ. About a mile from Lions — the early-tee-time stop.","Open","",1,"https://www.twogoosebbq.com/"),
("F03","Eggman ATX","NYC bodega breakfast sandwiches","The Picnic, 1720 Barton Springs Rd · Zilker","Daily 7–1:30","Bodega Classic BEC $8.95; The Big Mess $12.95","Half a mile from Butler Pitch & Putt.","Open","",1,"https://www.eggmanatx.com"),
("F04","Veracruz All Natural (the original bus)","Breakfast tacos","2505 Webberville Rd · East Austin","Mon–Wed 7–3, Thu–Sun 7–9","Migas taco","The teal school bus that started it, run by sisters Reyna and Maritza Vazquez. Alton Brown's favourite breakfast taco.","Open","",1,"https://www.veracruzallnatural.com/locations"),
("F05","David Doughie's Bagelry","Bagels","Fleet Coffee, 2427 Webberville Rd · East Austin","Thu–Sun mornings","Zhuggy Stardust $13.75; The O.G. smoked salmon $16","Barton Springs Mill grain, aged three days. Two doors from Veracruz.","Open","",1,"https://www.daviddoughies.com"),
("F06","La Santa Barbacha","Barbacoa tacos","2806 Manor Rd · East Austin","Daily 7–3","Benito taco $6; barbacoa taco $6","Sisters Daniela and Rosa Landaverde. Michelin Bib Gourmand 2024 and 2025; 2026 James Beard semifinalists.","Open","",1,"https://www.lasantabarbacha.com"),
("F07","Discada","Discada taquitos","Outside Chalmers, 1700 E Cesar Chavez · East Austin","Tue 4–9, Wed–Sat 12–9, Sun 12–4","3 taquitos $8.50; elote en vaso $7.50","Beef and pork cooked on a plough disc. Michelin recommended.","Open","",1,"https://www.discadatx.com"),
("F08","Parish Barbecue","Louisiana-inflected BBQ","Austin Beerworks Sprinkle Valley, 10300 Springdale Rd · NE Austin","Thu–Sun from 11","Prime brisket ½ lb $20; pulled duck with crispy skin ½ lb $25","Holden Fulco (ex-Franklin, InterStellar). Michelin Bib Gourmand Oct 2025. Not in our BBQ Field Guide.","Open","",1,"https://parishbarbecue.com"),
("F09","Distant Relatives","African American BBQ heritage","Meanwhile Brewing, 3901 Promontory Point · South Austin","Wed–Sun from noon","Smoked chicken with chile vinegar butter; house sausage","Damien Brockway. Michelin Bib Gourmand. Not in our BBQ Field Guide.","Open","",1,"https://www.distatantrelativesatx.com/"),
("F10","Patrizi's","Handmade pasta","The Vortex, 2307 Manor Rd · East Austin","Daily 5–9:30","Carbonara Alexandra $17; cacio e pepe $15","Cousins Nic and Matt Patrizi, on this patio since 2013. Fettuccine made daily.","Open","",1,"https://patrizis.com/manor-road"),
("F11","T-Loc's Sonora Hot Dogs","Sonoran dogs + burritos","5000 Burnet Rd · Rosedale","Tue–Sun, lunch (+ dinner Thu–Sat)","Hot dog con todo; carne asada burrito","Miguel Kaiser (Per Se alum) and Zulma Nataren, from Tucson. Buns flown in weekly.","Open","",1,"https://www.tlocs.com"),
("F12","Yeni's Fusion","Indonesian","Night Owl, 8315 Burnet Rd · North Austin","Tue–Sun 4–10","Empal gentong; beef rendang; batagor","Chef Yeni Rosdiyani from West Java. Halal.","Open","",1,"https://www.yenisfusion.com"),
("F13","Kai Zabb Thai","Thai fried chicken + curries","Celis Brewery, 10001 Metric Blvd · North Austin","Hours conflict between sources — confirm","Kai Zabb $17.99; panang with crispy chicken $17.99","Moved to Celis in June 2026. Infatuation Best New Restaurants 2025.","Open (moved)","Hours conflict",1,"https://www.kaizabb.com"),
("F14","El Marisquero Seafood","Sinaloa mariscos","2056 W Stassney Ln · South Austin","Daily 12–7","Aguachile rojo; ceviche 3 Amigos; Baja fish taco","Infatuation 8.5. BYOB.","Open","",1,"https://elmarisqueroseafoodtx.com"),
("F15","Pav Bhaji Express","Mumbai street food (veg)","30 N I-35 by Lady Bird Lake, + N MoPac by the Domain","Tue–Sun from noon, late on weekends","Special pav bhaji; vada pav; pani puri","The Statesman called it Austin's best Indian food truck (Apr 2026).","Open","",1,"https://www.statesman.com/entertainment/dining/article/pav-bhaji-express-north-austin-22208772.php"),
("F16","Cockti Juicy Fried Chicken","Fried chicken sandwiches","1309 Rosewood Ave · East Austin","Wed–Sun","Szechuan chicken sandwich $8.99","Army veteran Nick Lowell. Everything can be made gluten-friendly.","Open","",0,"https://cocktifriedchicken.co"),
("F17","R&B's Steak and Fries","Cheesesteaks","The Grackle, 1700 E 6th · East Austin","Daily 11–midnight","Cheesesteak $12.50; cheesesteak fries $16","New Jersey brothers Arman and Kris Elliott.","Open","",0,"https://www.rnbssteakandfries.com"),
("F18","Beirut","Lebanese","13752 Research Blvd · NW Austin","Tue–Sun","Chicken shawarma wrap $11; mixed grill $29","Family-owned; began as a secret menu.","Open","",0,"https://www.beirutatx.com"),
("F19","Pita Plus","Kosher Israeli","6719 N Lamar · North Austin","Sun–Thu 10–7","Turkey shawarma; schnitzel","The region's only kosher trailer.","Open","",0,"https://pitaplustx.com"),
("F20","Space Kat BBQ","BBQ, no brisket by design","2431 Webberville Rd · East Austin","Thu–Sun 11–5","Akaushi tri-tip; baby backs","Texas Monthly review May 2026.","Open","",0,"https://spacekatbbq.com/"),
("F21","Blue Apsara","Cambodian","1904 S Lamar · South Lamar","Wed–Sun lunch + dinner (not first-party)","Fish amok; nom pahng","The Statesman's #1 food truck for 2026; Infatuation Best New 2025. Couldn't confirm current hours first-hand.","Unclear","Status to confirm",0,"https://blueapsarakitchen.square.site/"),
("F22","Song La","Taiwanese","Thicket Food Park, 7800 S 1st · South Austin","Wed–Sun (Yelp only)","Chicken bites box; pork belly gua bao","Austin's first Taiwanese truck (2015).","Unclear","Status to confirm",0,"https://www.yelp.com/biz/song-la-austin"),
("F23","Cuantos Tacos","Mexico City tacos","1108 E 12th · East Austin","Tue–Sun","Suadero; cachete","Michelin Bib Gourmand. Truck may close as the Justin Ln storefront opens.","Unclear","May close soon",0,"https://guide.michelin.com/us/en/texas/austin_2958315/restaurant/cuantos-tacos"),
("F24","Wagyu Yume","A5 wagyu bowls","Location unconfirmed","—","Gyudon; A5 rice bowl","Current parking spot unknown.","Unclear","Location unknown",0,"https://www.selflane.com/bizs/wagyu-yume-food-truck_austin_tx"),
("F25","KG BBQ","Egyptian-Texas BBQ","Oddwood Brewing, 3108 Manor Rd","Thu–Sun","Brisket rice bowl $18.50","Infatuation 9.4. A mile from Morris Williams.","Open","Already in our BBQ Field Guide",0,"https://www.kgbbq.com/"),
("F26","Briscuits","BBQ on biscuits","Radio Coffee & Beer, 4204 Menchaca","Thu–Sun mornings","Brisket & jelly biscuit $17.50","Michelin Bib Gourmand.","Open","Already in our BBQ Field Guide",0,"https://briscuits.com/"),
("F27","Side Eye Pie","Wood-fired pizza","Meanwhile Brewing","Daily","The Local Trip","Infatuation 8.3.","Open","Already in our Pizza guide",0,"https://www.sideeyepie.com"),
("F28","The Marylander","Crab cakes, pit beef","2505 Webberville Rd","Fri–Tue 9–3","Crabcake sandwich $29","Infatuation 8.3.","Open","Already in our Wings guide",0,"https://www.marylanderfoodtruck.com/"),
]
cards=[]
for i,n,c,w,h,o,why,st,fl,rec,u in O:
    col={'Open':'#2D4A2B','Open (moved)':'#2D4A2B','Unclear':'#9a6b00'}[st]
    cards.append(f'<div class="c{" rec" if rec else ""}">{"<span class=star>★</span>" if rec else ""}<div class="id">{i} · <span style="color:{col}">{st}</span></div><div class="b">{html.escape(n)}</div><div class="k">{html.escape(c)}</div><div class="r"><b>Where</b> {html.escape(w)}</div><div class="r"><b>Hours</b> {html.escape(h)}</div><div class="r"><b>Order</b> {html.escape(o)}</div><div class="r">{html.escape(why)}</div>{f"<div class=f>{html.escape(fl)}</div>" if fl else ""}<a href="{u}" target="_blank">source ↗</a></div>')
out=f'''<!doctype html><meta charset=utf-8><title>Food truck field guide — options</title><style>body{{font:14px/1.45 -apple-system,Helvetica,sans-serif;background:#f4f1ea;color:#1b1f1a;margin:0;padding:28px}}h1{{font:600 28px Georgia,serif;margin:0 0 8px}}.key{{background:#fff;border:1px solid #ddd;padding:12px 14px;max-width:950px;margin-bottom:18px}}.g{{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:14px}}.c{{background:#fff;border:1px solid #ddd;padding:12px;position:relative}}.c.rec{{border:2px solid #2D4A2B}}.id{{font:600 11px ui-monospace,monospace}}.b{{font:600 18px Georgia,serif;margin:4px 0 2px}}.k{{color:#666;margin-bottom:6px}}.r{{font-size:13px;margin-top:4px}}.r b{{font:600 10px ui-monospace,monospace;text-transform:uppercase;letter-spacing:.08em;color:#2D4A2B;margin-right:4px}}.f{{background:#fff4d6;color:#7a5a00;font-size:12px;padding:3px 6px;margin-top:8px}}.star{{position:absolute;top:8px;right:10px;color:#2D4A2B;font-weight:700}}a{{color:#2D4A2B;font-size:12px;display:inline-block;margin-top:8px}}</style>
<h1>Austin Food Truck Field Guide: 28 options, pick 15</h1>
<div class="key"><b>★ with a green border</b> = my 15: all confirmed operating this month, none repeated from our BBQ, Pizza or Wings guides, spread across East, South and North Austin, mornings to late night. Status, locations, hours and prices were checked on 26 September 2026 from each truck's own site or ordering page; prices shown are what those pages list today. <span style="background:#fff4d6;padding:0 4px">Yellow</span> = something to confirm or a repeat. Knuckle Sandwich (Statesman list) has closed, so it isn't here. None of the munis except Butler Pitch &amp; Putt has a truck on site; I've noted the nearest course where it's close.</div>
<div class="g">{"".join(cards)}</div>'''
open('/sessions/admiring-pensive-ritchie/mnt/TheGrassyIssue/food-truck-options-2026-09-26.html','w').write(out)
json.dump(O,open('options.json','w'),indent=1)
print(len(O), sum(o[9] for o in O))
